version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: ./work_test/
    env_file: .env
    depends_on:
      - db
    ports:
      - 8000:9000